from flask import Flask, render_template_string, jsonify
import random

app = Flask(__name__)

# Список участников и их шансы
items = [
    ("Никита", 1),
    ("Арсений", 1),
    ("Максон", 1),
    ("Костя", 1),
    ("Илья", 1),
    ("Дима", 1),
    ("Саша", 1),
    ("Паша", 1),
]

total_weight = sum(weight for name, weight in items)

# HTML
HTML = """
<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8" />
<title>Колесо фортуны</title>
<style>
body { 
    text-align: center; 
    font-family: sans-serif; 
    margin-top: 50px; 
}
#wheel-container { 
    position: relative; 
    width: 400px; 
    height: 400px; 
    margin: auto; 
}
#wheel {
    width: 100%; 
    height: 100%; 
    border-radius: 50%;
    position: relative;
    border: 3px solid #000;
    overflow: hidden;
    /* transition will be set dynamically per-spin for random speed */
}

/* Arrow pointer that indicates the winner (points toward the wheel) */
#arrow {
    position: absolute;
    top: -20px;              /* adjust to place the arrow just above the wheel */
    left: 50%;
    transform: translateX(-50%);
    width: 0;
    height: 0;
    border-left: 18px solid transparent;
    border-right: 18px solid transparent;
    border-bottom: 26px solid #e33; /* arrow color */
    box-shadow: 0 2px 4px rgba(0,0,0,0.3);
    z-index: 5;
}

/* labels placed around the wheel */
.label {
    position: absolute;
    top: 50%;
    left: 50%;
    transform-origin: 0 0;
    font-weight: bold;
    white-space: nowrap;
    padding: 2px 6px;
    pointer-events: none;
    color: #111;
    text-shadow: 0 1px 0 rgba(255,255,255,0.6);
}

button { 
    margin-top: 20px; 
    padding: 12px 30px;
    font-size: 18px;
    background-color: #28a745;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}
button[disabled] {
    opacity: 0.6;
    cursor: not-allowed;
}
button:hover:not([disabled]) { 
    background-color: #218838;
}
#result { 
    margin-top: 20px; 
    font-size: 20px; 
    font-weight: bold;
    min-height: 24px;
}
</style>
</head>
<body>
<div id="wheel-container">
    <div id="arrow" aria-hidden="true"></div>
    <div id="wheel">
        <!-- Segments and labels will be generated by JavaScript -->
    </div>
</div>
<button id="spinBtn" onclick="spin()">Крутить</button>
<div id="result"></div>

<script>
let currentRotation = 0;

function createWheel() {
    const wheel = document.getElementById('wheel');
    wheel.innerHTML = ''; // clear
    const items = {{ items|tojson }};
    const totalWeight = items.reduce((sum, item) => sum + item[1], 0);
    let startAngle = 0;
    const gradientParts = [];
    const radius = wheel.clientWidth / 2 * 0.75; // distance from center for labels

    items.forEach(([name, weight], index) => {
        const segmentAngle = (weight / totalWeight) * 360;
        const endAngle = startAngle + segmentAngle;
        const color = `hsl(${(index / items.length) * 360}, 70%, 70%)`;
        gradientParts.push(`${color} ${startAngle}deg ${endAngle}deg`);

        // create label at middle angle
        const mid = startAngle + segmentAngle / 2;
        const label = document.createElement('div');
        label.className = 'label';
        // rotate to angle, move outward, then flip text if on bottom half
        const flip = (mid > 90 && mid < 270) ? 180 : 0;
        label.style.transform = `rotate(${mid}deg) translateX(${radius}px) rotate(${flip}deg)`;
        label.innerText = name;
        wheel.appendChild(label);

        startAngle = endAngle;
    });

    wheel.style.background = `conic-gradient(${gradientParts.join(',')})`;
}

window.onload = createWheel;

// basic spin function that requests server for a winner and rotates wheel to that segment
function spin() {
    const btn = document.getElementById('spinBtn');
    if (btn.disabled) return;
    btn.disabled = true;
    document.getElementById('result').innerText = '';

    fetch('/spin').then(r => r.json()).then(data => {
        const wheel = document.getElementById('wheel');
        const index = data.index;

        // compute cumulative start angle for the chosen index (recompute here to match client rendering)
        const items = {{ items|tojson }};
        const totalWeight = items.reduce((sum, item) => sum + item[1], 0);
        let startAngle = 0;
        for (let i = 0; i < index; i++) {
            startAngle += (items[i][1] / totalWeight) * 360;
        }
        const segmentAngle = (items[index][1] / totalWeight) * 360;
        const mid = startAngle + segmentAngle / 2;

        // spin to land mid at top (arrow position at 0deg). add full rotations for effect
        const spins = Math.floor(Math.random() * 4) + 4; // random full spins between 4 and 7
        const jitter = (Math.random() * (segmentAngle/2) - (segmentAngle/4)); // small variation
        const targetRotation = 360 * spins - mid + jitter;

        // set a random duration (speed) per spin
        const duration = (Math.random() * 3 + 3).toFixed(2); // 3.00 - 6.00 seconds
        wheel.style.transition = `transform ${duration}s cubic-bezier(0.33, 1, 0.68, 1)`;

        // apply rotation (accumulate to keep smooth multiple spins)
        currentRotation += targetRotation;
        wheel.style.transform = `rotate(${currentRotation}deg)`;

        // wait for transition end to show result and re-enable button
        const onEnd = (e) => {
            if (e.propertyName !== 'transform') return;
            document.getElementById('result').innerText = 'Победитель: ' + data.winner;
            btn.disabled = false;
            wheel.removeEventListener('transitionend', onEnd);
        };
        wheel.addEventListener('transitionend', onEnd);
    }).catch(err => {
        document.getElementById('result').innerText = 'Ошибка при запросе.';
        document.getElementById('spinBtn').disabled = false;
    });
}
</script>
</body>
</html>
"""

@app.route("/")
def home():
    return render_template_string(HTML, items=items)

@app.route("/spin")
def spin():
    names = [i[0] for i in items]
    weights = [i[1] for i in items]
    winner = random.choices(names, weights=weights, k=1)[0]
    return jsonify({
        "winner": winner,
        "index": names.index(winner),
        "count": len(names)
    })

if __name__ == "__main__":
    app.run(debug=True)
